#vcpkg
set(VCPKG_ROOT "$ENV{HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake")
if (APPLE)
    set(VCPKG_INCLUDE "$ENV{HOME}/vcpkg/installed/arm64-osx/include")
elseif (WIN32)
    set(VCPKG_INCLUDE "$ENV{HOME}/vcpkg/installed/x64-windows/include")
elseif (UNIX)
    set(VCPKG_INCLUDE "${CMAKE_CURRENT_SOURCE_DIR}/build/vcpkg_installed/x64-linux/include")
endif()
# set(CMAKE_TOOLCHAIN_FILE "$ENV{HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE STRING "VCPKG toolchain file")
set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}" )
message(STATUS "VCPKG_ROOT: ${VCPKG_ROOT}")
message(STATUS "VCPKG_INCLUDE: ${VCPKG_INCLUDE}")
message(STATUS "CMAKE_TOOLCHAIN_FILE: ${CMAKE_TOOLCHAIN_FILE}")
#nova
set(NOVA_INCLUDE "${CMAKE_CURRENT_SOURCE_DIR}/include")